title: devlopr
subtitle: A Portfolio Jekyll Theme Built for Developers
description: >-
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is
  optimized for speed and readability.
url: ''
baseurl: ''
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Shop
    url: /shop
  - text: Contact
    url: /contact
  - text: Styleguide
    url: /styleguide
  - text: Get Started
    url: /get-started
author_logo: profile.png
author: John Doe
author_bio: 'Hi, my name is John Doe. I built this site using devlopr-jekyll :D'
author_email: mail@sujaykundu.com
author_location: India
author_website_url: 'https://sujaykundu.com'
typewrite-text: >-
  devlopr is a jekyll theme built for developers. You can edit this in
  _config.yml file
author_work_experiences:
  - company_name: Google
    company_logo: google.png
    company_url: 'https://google.com'
    designation: Software Engineer
    description: Worked on various Google Products
    visibility: true
  - company_name: Microsoft
    company_logo: microsoft.png
    company_url: 'https://microsoft.com'
    designation: Azure Developer
    description: Worked on various Azure Cloud Products
    visibility: true
author_education_details:
  - college_logo: mit.png
    college_name: MIT
    college_url: 'https://mit.org'
    college_degree: CS Engineer
    description: Bachelor of Technology
    visibility: true
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: 'https://gamershub.in'
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: 'https://hack4r.com'
    visibility: true
twitter_username: johndoe
github_username: sujaykundu777
facebook_username: johndoe
linkedin_username: johndoe
behance_username: johndoe
instagram_username: johndoe
medium_username: johndoe
telegram_username: johndoe
dribbble_username: johndoe
flickr_username: johndoe
hyvor_talk_website_id: 476
wakatime_username: sujaykundu777
mailchimp_form_url: >-
  https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0
formspree_email: johndoe@gmail.com
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  products:
    output: true
  authors:
    output: true
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      permalink: '/blog/authors/:slug'
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
